"""Parity tests — backend port output vs. captured TS snapshots.

For each of the 23 captured fixtures, run `build_deck_from_upstream` and
compare structural fields against the TS-side snapshot generated by
`scroll-down-web/web/tests/unit/qa/_export-snapshots.test.ts`.

Intentional deviation: `scoreAfter` is absent from the backend DTO by
spoiler-safety contract. The parity check skips that field.

These tests log per-fixture deviations and assert a minimum match rate so
small narrative-text deltas don't fail the suite, but selection or rhythm
drift will.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from app.scroll_down_mlb.service import build_deck_from_upstream
from app.scroll_down_mlb.schemas import GenerationPolicy

_FIXTURES_DIR = (
    Path(__file__).parent / "fixtures" / "scroll_down_mlb" / "games"
)
_SNAPSHOTS_DIR = (
    Path(__file__).parent / "fixtures" / "scroll_down_mlb" / "snapshots"
)


def _fixture_ids() -> list[str]:
    return sorted(
        p.stem
        for p in _FIXTURES_DIR.glob("*.json")
        if p.stem.isdigit() and (_SNAPSHOTS_DIR / p.name).exists()
    )


def _load(path: Path) -> dict[str, Any]:
    with path.open() as f:
        return json.load(f)


@pytest.mark.parametrize("fixture_id", _fixture_ids())
def test_backend_deck_generates_without_error(fixture_id: str) -> None:
    """Every fixture must produce a non-blocked official deck."""
    payload = _load(_FIXTURES_DIR / f"{fixture_id}.json")
    outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
    if outcome.blocked:
        pytest.fail(
            f"Fixture {fixture_id} blocked by validation: "
            f"{[e.code for e in outcome.errors]}"
        )
    assert outcome.deck is not None
    assert outcome.deck.cards, f"Fixture {fixture_id} produced empty deck"


@pytest.mark.parametrize("fixture_id", _fixture_ids())
def test_backend_selects_same_play_indices_as_ts(fixture_id: str) -> None:
    """The set of play_index values selected for the deck should match
    the TS snapshot. Selection determinism is the load-bearing parity
    guarantee — narrative text can drift, but a play that was a force-
    include on the frontend must be a force-include on the backend."""
    payload = _load(_FIXTURES_DIR / f"{fixture_id}.json")
    snapshot = _load(_SNAPSHOTS_DIR / f"{fixture_id}.json")
    outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
    assert outcome.deck is not None

    backend_ids = {
        int(c.play.play_id)
        for c in outcome.deck.cards
        if c.type.value == "play" and c.play is not None
    }
    ts_ids = {
        c["playIndex"]
        for c in snapshot["cards"]
        if c.get("kind") == "play"
    }
    missing = ts_ids - backend_ids
    extra = backend_ids - ts_ids
    assert not missing and not extra, (
        f"Fixture {fixture_id} play selection drift: "
        f"missing from backend {sorted(missing)}, "
        f"extra in backend {sorted(extra)}"
    )


@pytest.mark.parametrize("fixture_id", _fixture_ids())
def test_backend_score_before_matches_ts(fixture_id: str) -> None:
    """For every selected play, scoreBefore must match the TS snapshot."""
    payload = _load(_FIXTURES_DIR / f"{fixture_id}.json")
    snapshot = _load(_SNAPSHOTS_DIR / f"{fixture_id}.json")
    outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
    assert outcome.deck is not None

    ts_by_idx = {
        c["playIndex"]: c
        for c in snapshot["cards"]
        if c.get("kind") == "play"
    }
    mismatches: list[str] = []
    for card in outcome.deck.cards:
        if card.type.value != "play" or card.play is None:
            continue
        pid = int(card.play.play_id)
        ts_card = ts_by_idx.get(pid)
        if not ts_card:
            continue
        sb = card.play.score_before
        ts_sb = ts_card.get("scoreBefore") or {}
        if not sb or sb.home != ts_sb.get("home") or sb.away != ts_sb.get("away"):
            mismatches.append(
                f"play {pid}: backend={sb} ts={ts_sb}"
            )
    assert not mismatches, (
        f"Fixture {fixture_id} scoreBefore drift on {len(mismatches)} cards: "
        + "; ".join(mismatches[:3])
    )


@pytest.mark.parametrize("fixture_id", _fixture_ids())
def test_backend_inning_and_half_match_ts(fixture_id: str) -> None:
    """Inning/half on every play card must match the TS snapshot — these
    drive rhythm planning so any drift cascades."""
    payload = _load(_FIXTURES_DIR / f"{fixture_id}.json")
    snapshot = _load(_SNAPSHOTS_DIR / f"{fixture_id}.json")
    outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
    assert outcome.deck is not None

    ts_by_idx = {
        c["playIndex"]: c
        for c in snapshot["cards"]
        if c.get("kind") == "play"
    }
    mismatches: list[str] = []
    for card in outcome.deck.cards:
        if card.type.value != "play" or card.play is None:
            continue
        pid = int(card.play.play_id)
        ts_card = ts_by_idx.get(pid)
        if not ts_card:
            continue
        if card.inning != ts_card.get("inning"):
            mismatches.append(
                f"play {pid}: inning backend={card.inning} ts={ts_card.get('inning')}"
            )
        if card.half != ts_card.get("inningHalf"):
            mismatches.append(
                f"play {pid}: half backend={card.half} ts={ts_card.get('inningHalf')}"
            )
    assert not mismatches, (
        f"Fixture {fixture_id} inning/half drift: "
        + "; ".join(mismatches[:3])
    )


@pytest.mark.parametrize("fixture_id", _fixture_ids())
def test_backend_runs_scored_matches_ts(fixture_id: str) -> None:
    """runsScoredOnPlay (backend) must equal scoreAfter - scoreBefore (TS)."""
    payload = _load(_FIXTURES_DIR / f"{fixture_id}.json")
    snapshot = _load(_SNAPSHOTS_DIR / f"{fixture_id}.json")
    outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
    assert outcome.deck is not None

    ts_by_idx = {
        c["playIndex"]: c
        for c in snapshot["cards"]
        if c.get("kind") == "play"
    }
    mismatches: list[str] = []
    for card in outcome.deck.cards:
        if card.type.value != "play" or card.play is None:
            continue
        pid = int(card.play.play_id)
        ts_card = ts_by_idx.get(pid)
        if not ts_card:
            continue
        ts_runs = (
            (ts_card["scoreAfter"]["home"] - ts_card["scoreBefore"]["home"])
            + (ts_card["scoreAfter"]["away"] - ts_card["scoreBefore"]["away"])
        )
        if card.play.runs_scored_on_play != max(0, ts_runs):
            mismatches.append(
                f"play {pid}: backend={card.play.runs_scored_on_play} ts={ts_runs}"
            )
    assert not mismatches, (
        f"Fixture {fixture_id} runs delta drift: "
        + "; ".join(mismatches[:3])
    )


@pytest.mark.parametrize("fixture_id", _fixture_ids())
def test_backend_rhythm_card_kinds_match_ts(fixture_id: str) -> None:
    """The ordered list of rhythm-card kinds (inning-transition / quiet-
    stretch / late-game / final-setup) must match the TS snapshot."""
    payload = _load(_FIXTURES_DIR / f"{fixture_id}.json")
    snapshot = _load(_SNAPSHOTS_DIR / f"{fixture_id}.json")
    outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
    assert outcome.deck is not None

    rhythm_kind_map = {
        "rhythm": "rhythm",
        "final_setup": "final-setup",
    }
    backend_rhythm_seq = [
        # The backend collapses inning-transition + quiet-stretch + late-game
        # into the single `rhythm` DTO type. Map back via card.id which keeps
        # the original kind suffix from rhythm_planner (-tx-, -qs-, -lg-).
        ("inning-transition" if "-tx-" in c.id
         else "quiet-stretch" if "-qs-" in c.id
         else "late-game" if "-lg-" in c.id
         else rhythm_kind_map.get(c.type.value, c.type.value))
        for c in outcome.deck.cards
        if c.type.value in ("rhythm", "final_setup")
    ]
    ts_rhythm_seq = [
        c["kind"]
        for c in snapshot["cards"]
        if c.get("kind")
        in ("inning-transition", "quiet-stretch", "late-game", "final-setup")
    ]
    assert backend_rhythm_seq == ts_rhythm_seq, (
        f"Fixture {fixture_id} rhythm sequence drift: "
        f"backend={backend_rhythm_seq} ts={ts_rhythm_seq}"
    )


def test_parity_summary_min_pass_rate() -> None:
    """Aggregate summary: at least 80% of fixtures should produce a deck
    with the same play-card count as the TS snapshot. This is a coarser
    gate than the per-card tests above; it catches systemic drift while
    tolerating per-fixture edge cases."""
    fixtures = _fixture_ids()
    matches = 0
    for fid in fixtures:
        payload = _load(_FIXTURES_DIR / f"{fid}.json")
        snapshot = _load(_SNAPSHOTS_DIR / f"{fid}.json")
        outcome = build_deck_from_upstream(payload, policy=GenerationPolicy.official)
        if outcome.blocked or outcome.deck is None:
            continue
        backend_play_count = sum(
            1 for c in outcome.deck.cards if c.type.value == "play"
        )
        ts_play_count = sum(1 for c in snapshot["cards"] if c.get("kind") == "play")
        if backend_play_count == ts_play_count:
            matches += 1
    rate = matches / len(fixtures) if fixtures else 0
    assert rate >= 0.80, (
        f"Backend deck-size parity rate is {rate:.0%} ({matches}/{len(fixtures)}). "
        "This indicates systemic selection drift between backend and TS builder."
    )
